---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-example-octodex
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.aws-example-octodex: glob:1.4.*
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-example-octodex
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aws-example-octodex
    spec:
      containers:
      - name: aws-example-octodex
        image: sigmaeibon/flux-example:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
